# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 83b8661c52fb9ba5508bec32d8c6fe05de3a3c4f3acb885f27597142de45e3ad317cd0350f7e12dd2562572bd5bdb8890541a02fb473fe455fcb65933aa92d46

test:
  secret_key_base: b786e8e64ae1bac876e2a2acf76d8212fb74154e6ca6f776ed1614db565ffa9dcdf099c37fd2b7ec791f85ce6e878522e6305fa3651cd37778cb3f35b1db55a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
